<script>
    var current = $("#games");
    current.siblings().removeClass("active");
    current.addClass("active");
</script>
<a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'games', 'action'=>'add')) ?>" class="btn btn-info mbtn">Add Game</a>
<table class="table">
    <thead>
    <tr>
        <td width="5%">ID</td>
        <td width="15%">Name</td>
        <td width="25%">Description</td>
        <td width="10%">Category</td>
        <td width="15%">Url</td>
        <td width="10%">Rating</td>
        <td width="20%">Actions</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->list as $array => $item) { ?>
        <tr>
            <td><?php echo $item['id']; ?></td>
            <td><?php echo $item['title']; ?></td>
            <td><?php echo $item['desc']; ?></td>
            <td><?php echo $item['cat']; ?></td>
            <td><?php echo $item['url']; ?></td>
            <td><?php echo $item['rating']; ?></td>
            <td>
                <a href="/admin/games/edit/id/<?php echo $item['id']; ?>" class="btn btn-info">Edit</a>
                <a href="/admin/games/remove/id/<?php echo $item['id']; ?>" class="btn btn-danger">Remove</a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>