<aside id="top-zone" class="section">
    <?php foreach($this->maingame as $array => $item) { ?>
    <img src="/images/content/games/<?php echo $item['main_img']; ?>" alt="">
    <div class="content">
        <h1><a href="<?php echo mb_strtolower(str_replace(" ", "-", $item['title'])); ?>.html"><?php echo $item['title']; ?></a></h1>
        <p><?php echo $item['desc']; ?></p>
        <p class="btn-set">
            <a href="<?php echo $item['url']; ?>" target="_blank" rel="nofollow" class="btn">play now</a>
            <a href="<?php echo $this->url(array('controller'=>'index','action'=>'item', 'slug' => mb_strtolower(str_replace(" ", "-", $item['title']))), 'item', true); ?>" class="btn trailer">watch trailer</a></p>
    </div>
    <?php } ?>
</aside>

<div class="slider owl-carousel">
    <?php foreach($this->slider as $array => $item) { ?>
    <div>
        <a href="<?php echo mb_strtolower(str_replace(" ", "-", $item['title'])); ?>.html"><img src="/images/content/games/<?php echo $item['main_img']; ?>" alt=""></a>
        <span class="label">new</span>
        <div class="item-title">
            <h3><a href="<?php echo mb_strtolower(str_replace(" ", "-", $item['title'])); ?>.html"><?php echo $item['title']; ?></a></h3>
            <p class="date">First Released <?php echo date("M d, Y", $item['date']); ?></p>
        </div>
    </div>
    <?php } ?>
</div>
<?php foreach($this->items as $array => $item) { ?>
<div class="game-item">
    <div class="video-wrap">
        <?php if(!empty($item['trailer'])) { ?>
        <iframe width="100%" height="305" src="<?php echo $item['trailer']; ?>" frameborder="0" allowfullscreen=""></iframe>
        <?php } else { ?>
            <img src="/images/content/games/<?php echo $item['main_img']; ?>" alt="">
        <?php } ?>
    </div>
    <div class="content-wrap">
        <div class="title-wrap">
            <div class="title">
                <h3><a href="<?php echo mb_strtolower(str_replace(" ", "-", $item['title'])); ?>.html"><?php echo $item['title']; ?></a></h3>
                <p class="date">First Released <?php echo date("M d, Y", $item['date']); ?></p>
            </div>
            <div class="progressbar" data-value="<?php echo $item['rating']; ?>"></div>
        </div>
        <div class="description">
            <?php echo $item['desc']; ?>
        </div>
        <p class="btn-set">
            <a href="<?php echo $item['url']; ?>" class="btn" rel="nofollow" target="_blank">play now</a>
            <a href="<?php echo $this->url(array('controller'=>'index','action'=>'item', 'slug' => mb_strtolower(str_replace(" ", "-", $item['title']))), 'item', true); ?>" class="btn white">Info</a>
        </p>
    </div>
</div>
<?php } ?>