<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard | Check Games</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/admin.css">
</head>
<body>
<div class="wrap">
    <div class="header">
        <div class="page-header">
            <h1>Dashboard</h1>
        </div>
        <ul class="nav nav-pills">
            <li id="home" role="presentation" class="active"><a href="/admin/index/index">Home</a></li>
            <li id="games" role="presentation"><a href="/admin/games/index">Games</a></li>
            <li id="categories" role="presentation"><a href="/admin/categories/index">Categories</a></li>
            <li id="slider" role="presentation"><a href="/admin/slider/index">Slider</a></li>
            <li id="pages" role="presentation"><a href="/admin/pages/index">Pages</a></li>
            <li id="settings" role="presentation"><a href="/admin/settings/index">Settings</a></li>
        </ul>
    </div>
    <div class="content">
        <?php echo $this->layout()->content; ?>
    </div>
    <div class="hfooter"></div>
</div>
    <div class="footer">
        <div class="wr">
            <p><?php echo date("Y"); ?> &copy; <?php echo $_SERVER["SERVER_NAME"]; ?></p>
        </div>
    </div>
</body>
</html>
